#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-maintenance-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="maintenance"
  local plugin_description="Manage the maintenance mode for an app"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    maintenance:custom-page <app>, Imports a tarball from stdin; should contain at least maintenance.html
    maintenance:off <app>, Take the app out of maintenance mode
    maintenance:on <app>, Put the app into maintenance mode
    maintenance:report [<app>] [<flag>], Displays an maintenance report for one or more apps
help_content
}
