#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

maintenance-off-cmd() {
  declare desc="take the app out of maintenance mode"
  declare APP="$2"
  local NGINX_CONF_D="$DOKKU_ROOT/$APP/nginx.conf.d"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  dokku_log_info1 "Disabling maintenance mode for $APP..."
  [[ -f "$NGINX_CONF_D/maintenance.conf" ]] && rm "$NGINX_CONF_D/maintenance.conf"
  restart_nginx
  dokku_log_verbose "done"
}

maintenance-off-cmd "$@"
