#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/nginx-vhosts/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

maintenance-on-cmd() {
  declare desc="put the app into maintenance mode"
  declare cmd="maintenance:on"
  [[ "$1" == "$cmd" ]] && shift 1

  # Support --app/$DOKKU_APP_NAME flag by reordering args into "$cmd $DOKKU_APP_NAME $@"
  local argv=("$@")
  [[ -n "$DOKKU_APP_NAME" ]] && set -- $DOKKU_APP_NAME $@
  ##

  declare APP="$1"
  local NGINX_CONF_D="$DOKKU_ROOT/$APP/nginx.conf.d"
  local MAINTENANCE_APP_D="$DOKKU_ROOT/$APP/maintenance"

  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  dokku_log_info1 "Enabling maintenance mode for $APP..."
  [[ -d "$NGINX_CONF_D" ]] || mkdir "$NGINX_CONF_D"

  if [[ ! -d "$MAINTENANCE_APP_D" ]]; then
    mkdir "$MAINTENANCE_APP_D"
    cp "$MAINTENANCE_PLUGIN_ROOT/templates/maintenance.html" "$MAINTENANCE_APP_D"
  fi

  cp "$MAINTENANCE_PLUGIN_ROOT/templates/maintenance.conf" "$NGINX_CONF_D"
  sed -i "s,{APP_ROOT},$DOKKU_ROOT/$APP," "$NGINX_CONF_D/maintenance.conf"
  restart_nginx
  dokku_log_verbose "done"
}

maintenance-on-cmd "$@"
