location ~* ^(?!/\.well-known/acme-challenge).*$ {
  root {MAINTENANCE_ROOT};
  try_files $uri =533;
}

error_page 533 =503 @maintenance;

location @maintenance {
  root {MAINTENANCE_ROOT};
  rewrite ^(.*)$ /maintenance.html break;
}
